--- #YAML:1.0
name:                   Munin-Plugin-ApacheRequest
version:                0.03
abstract:               Monitor Apache requests with Munin
author:
  - Barbie <barbie@cpan.org>

license:                artistic_2
distribution_type:      module
installdirs:            site

requires:
  perl:                         5.006
recommends:
  Test::CPAN::Meta:             0
  Test::CPAN::Meta::JSON:       0
  Test::Pod:                    1.00
  Test::Pod::Coverage:          0.08
build_requires:
  IO::File:                     0
  Test::Trap:                   0
  Test::More:                   0.70

provides:
  Munin::Plugin::ApacheRequest:
    file:     lib/Munin/Plugin/ApacheRequest.pm
    version:  0.03
no_index:
  directory:
    - t
    - examples

resources:
  license:    http://www.perlfoundation.org/artistic_license_2_0
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Munin-Plugin-ApacheRequest
  repository: http://github.com/barbie/munin-plugin-apacherequest

meta-spec:
   version:   1.4
   url:       http://module-build.sourceforge.net/META-spec-v1.4.html
generated_by: Hand 1.0

